version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.2
    container_name: thulobazaar-typesense
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=your-api-key-change-in-production
      - TYPESENSE_SEARCH_ONLY_API_KEY=your-search-only-key
    command: '--data-dir /data --api-key=your-api-key-change-in-production --search-only-api-key=your-search-only-key --listen-port 8108 --enable-cors'
    restart: unless-stopped

volumes:
  typesense-data: